### PR TITLE
[CI] Release binaries workflow added

### LINKED ISSUE #38: [CI] Build and release needed for each WASM filter
**Current Behavior**
This repo's releases do not contain built binaries of each WASM filter.

**Desired Behavior**
Upon GH release, a binary for each filter should be captured as an artifact.

### PR DESCRIPTION
**Pull request by felixfaisal**
**Description**
It compiles individual filters and uploads the binary as an artifact
[Working example](https://github.com/felixfaisal/wasm-filters/actions/runs/1658978731)

This PR Fixes #38 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by felixfaisal** [comment]
Hey @leecalcote @utkarsh-pro let me know if you want me to rebase, since I have a few line commits

**Comment by Revolyssup** [comment]
@felixfaisal  Instead of compiling for each filter separately, can you do it a little more intelligently by looping through all directories in root, and whichever one has Cargo.toml, you can compile and upload the binary. So that in future as more filters get added, we dont have to keep coming back to change the workflow.

**Comment by felixfaisal** [comment]
@Revolyssup I can do that, But I would still need to correctly identify the WASM binary path which is quite difficult If I run a loop. Do you have any suggestions on how I could tackle that?

**Comment by Revolyssup** [comment]
> Author

Use this script to compile all binaries into one tar.
mkdir wasm-filters
for d in */ ; do
    cd "$d"
    cargo=$(ls | grep "Cargo.toml")
    if [ "$cargo" != ""  ];then
        wasm-pack build --release
        cd pkg
        file=$(ls | grep "wasm$")
        if [ "$file" != "" ]; then
            cp "$file" ../../wasm-filters/"$file"
        fi
        cd ..
    fi
    cd ..
done
tar -czvf wasm-filters.tar.gz ./wasm-filters

**Comment by leecalcote** [comment]
Let's give this a go....

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
And so it begins, @felixfaisal...

**Pull request merged**
