### PR TITLE
[README] Update community drive access message and link to community member form

### LINKED ISSUE #14: [README] Update README Community Section
**Description**
The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)

**Expected Behavior**
Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

**Screenshots**
img
--

**Resources**
Refer to the [Contributing guide](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#contributing)

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

### PR DESCRIPTION
**Pull request by josephmidura**
1. Update community drive access message and link to community member form
2. Fix two spelling errors on the page

Signed-off-by: Joseph Midura <josephmidura632@gmail.com>

**Description**

This PR Fixes #14 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Anita-ihuman — COMMENTED** [review]
Thank you for picking up this issue.
Please remove the community drive link we don't need it there anymore.
Then we are good to go.

**Comment by josephmidura** [comment]
Ok, the link is removed. ✅

**Review by Anita-ihuman — COMMENTED** [review]
Can you please use these exact words for consistency across the repositories?
"To Access Community Drive, fill Community Member Form"

**Comment by josephmidura** [comment]
I'm confused. I thought I should reference the [Layer5 template](https://github.com/layer5io/layer5-repo-template) for this issue.

**Review by Anita-ihuman — APPROVED** [review]

**Comment by Anita-ihuman** [comment]
> I'm confused. I thought I should reference the [Layer5 template](https://github.com/layer5io/layer5-repo-template) for this issue.

I apologize for that. I must have mixed it up. Well, we are good to go.

**Comment by josephmidura** [comment]
No problem. I just wanted to make sure I did what was expected.

**Pull request merged**
