### PR TITLE
Added Slack Badge 

### LINKED ISSUE #17: [README] Need to fix Slack badge
**Description**

<a href="https://github.com/layer5io/wasm-filters/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. For attractive look, we added some badges also.
But, there's a Slack badge failing, need to fix that. 
 
### Example Screenshot

**Current Behavior**

image

**Desired Behavior**
image

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

### PR DESCRIPTION
**Pull request by includestdlibrary**
**Description**

This PR Fixes #17 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by sayantan1413 — CHANGES_REQUESTED** [review]
hey @includestdlibrary you have done the thing correctly but to maintain the consistency with the other links you can use 
`[Slack](http://slack.layer5.io)`
instead of the anchor tag.

**Comment by includestdlibrary** [comment]
> 
> 
> hey @includestdlibrary you have done the thing correctly but to maintain the consistency with the other links you can use
> `[Slack](http://slack.layer5.io)`
> instead of the anchor tag.

Okay :)

**Review by sayantan1413 — APPROVED** [review]
Looks good to me. Great work @includestdlibrary .

**Review by leecalcote — APPROVED** [review]
Nice. ✔️

**Pull request merged**
